/**
 * index.ts – The algorithm registry.
 *
 * The registry is a central lookup table that maps kebab-case algorithm ids
 * (e.g. `"bubble-sort"`) to their `AlgorithmModule` objects. The sidebar
 * builds its category tree from `getAllAlgorithms()`, and the store resolves
 * a selected id with `getAlgorithm()`.
 *
 * Every algorithm file registers itself here, so this file grows exactly in
 * lockstep with the algorithm library. Keeping registration explicit (rather
 * than glob-importing the folder) keeps the module graph obvious and lets the
 * TypeScript compiler verify every reference at build time.
 */

import type { AlgorithmModule } from "@/types";

/** The one source of truth: id → module. */
const registry = new Map<string, AlgorithmModule>();

// ----------------------------------------------------------------------
// Algorithm registrations.
//
// Every algorithm module registers itself here with a single import + call,
// so the registry grows exactly in lockstep with the algorithm library.
// ----------------------------------------------------------------------

import bubbleSort from "./algo/sort/bubble-sort";
import bucketSort from "./algo/sort/bucket-sort";
import cocktailShakerSort from "./algo/sort/cocktail-shaker-sort";
import combSort from "./algo/sort/comb-sort";
import countingSort from "./algo/sort/counting-sort";
import heapSort from "./algo/sort/heap-sort";
import insertionSort from "./algo/sort/insertion-sort";
import introsort from "./algo/sort/introsort";
import mergeSortBottomUp from "./algo/sort/merge-sort-bottom-up";
import mergeSortTopDown from "./algo/sort/merge-sort-top-down";
import monkeySort from "./algo/sort/monkey-sort";
import patienceSort from "./algo/sort/patience-sort";
import quickSort3Way from "./algo/sort/quick-sort-3-way";
import quickSortHoare from "./algo/sort/quick-sort-hoare";
import quickSortLomuto from "./algo/sort/quick-sort-lomuto";
import radixSortLsd from "./algo/sort/radix-sort-lsd";
import radixSortMsd from "./algo/sort/radix-sort-msd";
import selectionSort from "./algo/sort/selection-sort";
import shellSort from "./algo/sort/shell-sort";
import smoothSort from "./algo/sort/smooth-sort";
import timSort from "./algo/sort/tim-sort";
import linearSearch from "./algo/search/linear-search";
import binarySearchIterative from "./algo/search/binary-search-iterative";
import binarySearchLowerBound from "./algo/search/binary-search-lower-bound";
import binarySearchRecursive from "./algo/search/binary-search-recursive";
import binarySearchUpperBound from "./algo/search/binary-search-upper-bound";
import exponentialSearch from "./algo/search/exponential-search";
import interpolationSearch from "./algo/search/interpolation-search";
import jumpSearch from "./algo/search/jump-search";
import ternarySearch from "./algo/search/ternary-search";
import bfs from "./algo/graph/bfs";
import bidirectionalBfs from "./algo/graph/bidirectional-bfs";
import dfsIterative from "./algo/graph/dfs-iterative";
import dfsRecursive from "./algo/graph/dfs-recursive";
import floodFillBfs from "./algo/graph/flood-fill-bfs";
import floodFillDfs from "./algo/graph/flood-fill-dfs";
import gabowScc from "./algo/graph/gabow-scc";
import hierholzerEulerian from "./algo/graph/hierholzer-eulerian";
import hopcroftKarp from "./algo/flow/hopcroft-karp";
import hungarian from "./algo/flow/hungarian";
import kosarajuScc from "./algo/graph/kosaraju-scc";
import aStar from "./algo/path/a-star";
import bellmanFord from "./algo/path/bellman-ford";
import blossom from "./algo/flow/blossom";
import dijkstraFibonacci from "./algo/path/dijkstra-fibonacci";
import dijkstraHeap from "./algo/path/dijkstra-heap";
import dijkstraMatrix from "./algo/path/dijkstra-matrix";
import floydWarshall from "./algo/path/floyd-warshall";
import johnson from "./algo/path/johnson";
import karpMinimumMeanCycle from "./algo/path/karp-minimum-mean-cycle";
import shortestPathDag from "./algo/path/shortest-path-dag";
import spfa from "./algo/path/spfa";
import kruskal from "./algo/mst/kruskal";
import treeCenter from "./algo/tree/tree-center";
import treeDiameter from "./algo/tree/tree-diameter";
import treeEulerTour from "./algo/tree/tree-euler-tour";
import treeIsomorphism from "./algo/tree/tree-isomorphism";
import lcaBinaryLifting from "./algo/tree/lca-binary-lifting";
import lcaEulerSparse from "./algo/tree/lca-euler-sparse";
import lcaTarjanOffline from "./algo/tree/lca-tarjan-offline";
import centroidDecomposition from "./algo/tree/centroid-decomposition";
import heavyLightDecomposition from "./algo/tree/heavy-light-decomposition";
import rerootingDp from "./algo/tree/rerooting-dp";
import knuthMorrisPratt from "./algo/string/knuth-morris-pratt";
import zAlgorithm from "./algo/string/z-algorithm";
import rabinKarpSingle from "./algo/string/rabin-karp-single";
import rabinKarpDouble from "./algo/string/rabin-karp-double";
import manacher from "./algo/string/manacher";
import suffixArrayDoubling from "./algo/string/suffix-array-doubling";
import suffixArrayDc3 from "./algo/string/suffix-array-dc3";
import lcpKasai from "./algo/string/lcp-kasai";
import suffixAutomaton from "./algo/string/suffix-automaton";
import suffixTreeUkkonen from "./algo/string/suffix-tree-ukkonen";
import ahoCorasick from "./algo/string/aho-corasick";
import eertree from "./algo/string/eertree";
import boyerMoore from "./algo/string/boyer-moore";
import boothMinimalRotation from "./algo/string/booth-minimal-rotation";
import duvalLyndon from "./algo/string/duval-lyndon";
import longestCommonSubstring from "./algo/string/longest-common-substring";
import longestCommonPrefixDp from "./algo/string/longest-common-prefix-dp";
import zAlgorithmOnTree from "./algo/string/z-algorithm-on-tree";
import rollingHash2d from "./algo/string/rolling-hash-2d";
import prefixFunctionAuto from "./algo/string/prefix-function-auto";
import euclidGcd from "./algo/math/euclid-gcd";
import extendedEuclid from "./algo/math/extended-euclid";
import binaryExponentiation from "./algo/math/binary-exponentiation";
import matrixExponentiation from "./algo/math/matrix-exponentiation";
import sieveEratosthenes from "./algo/math/sieve-eratosthenes";
import linearSieve from "./algo/math/linear-sieve";
import millerRabin from "./algo/math/miller-rabin";
import pollardRho from "./algo/math/pollard-rho";
import fermatLittle from "./algo/math/fermat-little";
import eulerTotient from "./algo/math/euler-totient";
import modularInverse from "./algo/math/modular-inverse";
import crtCoprime from "./algo/math/crt-coprime";
import crtGeneralized from "./algo/math/crt-generalized";
import lucasTheorem from "./algo/math/lucas-theorem";
import mobiusInversion from "./algo/math/mobius-inversion";
import gaussianElimination from "./algo/math/gaussian-elimination";
import gaussianEliminationGf2 from "./algo/math/gaussian-elimination-gf2";
import bareissFractionFree from "./algo/math/bareiss-fraction-free";
import tonelliShanks from "./algo/math/tonelli-shanks";
import babyStepGiantStep from "./algo/math/baby-step-giant-step";
import discreteRoot from "./algo/math/discrete-root";
import fftCooleyTukey from "./algo/math/fft-cooley-tukey";
import ntt from "./algo/math/ntt";
import polynomialInversion from "./algo/math/polynomial-inversion";
import polynomialLogExp from "./algo/math/polynomial-log-exp";
import lis from "./algo/dp/lis";
import lcs from "./algo/dp/lcs";
import shortestCommonSupersequence from "./algo/dp/shortest-common-supersequence";
import editDistance from "./algo/dp/edit-distance";
import knapsack01 from "./algo/dp/knapsack-01";
import knapsackComplete from "./algo/dp/knapsack-complete";
import knapsackMultiple from "./algo/dp/knapsack-multiple";
import subsetSum from "./algo/dp/subset-sum";
import bitmaskTsp from "./algo/dp/bitmask-tsp";
import digitDp from "./algo/dp/digit-dp";
import intervalMatrixChain from "./algo/dp/interval-matrix-chain";
import treeDpIndependentSet from "./algo/dp/tree-dp-independent-set";
import treeDpRerooting from "./algo/dp/tree-dp-rerooting";
import dagShortestDp from "./algo/dp/dag-shortest-dp";
import dagLongestDp from "./algo/dp/dag-longest-dp";
import countingDp from "./algo/dp/counting-dp";
import probabilityDp from "./algo/dp/probability-dp";
import divideConquerDp from "./algo/dp/divide-conquer-dp";
import knuthOptimization from "./algo/dp/knuth-optimization";
import aliensTrick from "./algo/dp/aliens-trick";
import monotonicQueueDp from "./algo/dp/monotonic-queue-dp";
import nim from "./algo/game/nim";
import misereNim from "./algo/game/misere-nim";
import spragueGrundy from "./algo/game/sprague-grundy";
import minimax from "./algo/game/minimax";
import alphaBeta from "./algo/game/alpha-beta";
import wythoff from "./algo/game/wythoff";
import dotCrossProduct from "./algo/geo/dot-cross-product";
import segmentIntersection from "./algo/geo/segment-intersection";
import sweepLineSegmentIntersection from "./algo/geo/sweep-line-segment-intersection";
import pointInPolygonRay from "./algo/geo/point-in-polygon-ray";
import pointInPolygonWinding from "./algo/geo/point-in-polygon-winding";
import convexHullGraham from "./algo/geo/convex-hull-graham";
import convexHullMonotone from "./algo/geo/convex-hull-monotone";
import convexHullJarvis from "./algo/geo/convex-hull-jarvis";
import closestPairOfPoints from "./algo/geo/closest-pair-of-points";
import rotatingCalipers from "./algo/geo/rotating-calipers";
import polygonAreaShoelace from "./algo/geo/polygon-area-shoelace";
import minEnclosingCircleWelzl from "./algo/geo/min-enclosing-circle-welzl";
import halfPlaneIntersection from "./algo/geo/half-plane-intersection";
import staticArray from "./algo/ds/static-array";
import dynamicArray from "./algo/ds/dynamic-array";
import singlyLinkedList from "./algo/ds/singly-linked-list";
import doublyLinkedList from "./algo/ds/doubly-linked-list";
import circularLinkedList from "./algo/ds/circular-linked-list";
import skipList from "./algo/ds/skip-list";
import stackArray from "./algo/ds/stack-array";
import stackLinked from "./algo/ds/stack-linked";
import queueArray from "./algo/ds/queue-array";
import queueLinked from "./algo/ds/queue-linked";
import deque from "./algo/ds/deque";
import priorityQueue from "./algo/ds/priority-queue";
import monotonicQueue from "./algo/ds/monotonic-queue";
import monotonicStack from "./algo/ds/monotonic-stack";
import minStack from "./algo/ds/min-stack";
import unrolledLinkedList from "./algo/ds/unrolled-linked-list";
import xorLinkedList from "./algo/ds/xor-linked-list";
import sortedLinkedList from "./algo/ds/sorted-linked-list";
import concurrentQueue from "./algo/ds/concurrent-queue";
import cyclicBuffer from "./algo/ds/cyclic-buffer";
import binaryTree from "./algo/ds/binary-tree";
import bst from "./algo/ds/bst";
import avlTree from "./algo/ds/avl-tree";
import redBlackTree from "./algo/ds/red-black-tree";
import splayTree from "./algo/ds/splay-tree";
import treap from "./algo/ds/treap";
import bTree from "./algo/ds/b-tree";
import bPlusTree from "./algo/ds/b-plus-tree";
import trie from "./algo/ds/trie";
import ternarySearchTrie from "./algo/ds/ternary-search-trie";
import suffixTrie from "./algo/ds/suffix-trie";
import fenwickTree from "./algo/ds/fenwick-tree";
import fenwickTreeRange from "./algo/ds/fenwick-tree-range";
import segmentTreeRecursive from "./algo/ds/segment-tree-recursive";
import segmentTreeIterative from "./algo/ds/segment-tree-iterative";
import segmentTreeLazy from "./algo/ds/segment-tree-lazy";
import persistentSegmentTree from "./algo/ds/persistent-segment-tree";
import dynamicSegmentTree from "./algo/ds/dynamic-segment-tree";
import binaryHeap from "./algo/ds/binary-heap";
import fibonacciHeap from "./algo/ds/fibonacci-heap";
import pairingHeap from "./algo/ds/pairing-heap";
import leftistHeap from "./algo/ds/leftist-heap";
import skewHeap from "./algo/ds/skew-heap";
import binomialHeap from "./algo/ds/binomial-heap";
import daryHeap from "./algo/ds/dary-heap";
import adjacencyMatrix from "./algo/ds/adjacency-matrix";
import adjacencyList from "./algo/ds/adjacency-list";
import edgeList from "./algo/ds/edge-list";
import incidenceMatrix from "./algo/ds/incidence-matrix";
import csr from "./algo/ds/csr";
import hashMapChaining from "./algo/ds/hash-map-chaining";
import hashMapOpen from "./algo/ds/hash-map-open";
import linkedHashMap from "./algo/ds/linked-hash-map";
import hashSet from "./algo/ds/hash-set";
import dsu from "./algo/ds/dsu";
import persistentDsu from "./algo/ds/persistent-dsu";
import kadane from "./algo/special/kadane";
import kadane2d from "./algo/special/kadane-2d";
import runLengthEncoding from "./algo/special/run-length-encoding";
import huffmanCoding from "./algo/special/huffman-coding";
import bloomFilter from "./algo/special/bloom-filter";
import countMinSketch from "./algo/special/count-min-sketch";
import simulatedAnnealing from "./algo/special/simulated-annealing";
import hillClimbing from "./algo/special/hill-climbing";
import monteCarlo from "./algo/special/monte-carlo";
import lasVegas from "./algo/special/las-vegas";
import boruvka from "./algo/mst/boruvka";
import primHeap from "./algo/mst/prim-heap";
import primMatrix from "./algo/mst/prim-matrix";
import secondBestMst from "./algo/mst/second-best-mst";
import fordFulkerson from "./algo/flow/ford-fulkerson";
import edmondsKarp from "./algo/flow/edmonds-karp";
import minCut from "./algo/flow/min-cut";
import minCostMaxFlow from "./algo/flow/min-cost-max-flow";
import boykovKolmogorov from "./algo/flow/boykov-kolmogorov";
import costScaling from "./algo/flow/cost-scaling";
import dinic from "./algo/flow/dinic";
import pushRelabel from "./algo/flow/push-relabel";
import lexicographicBfs from "./algo/graph/lexicographic-bfs";
import tarjanArticulationPoints from "./algo/graph/tarjan-articulation-points";
import tarjanBridges from "./algo/graph/tarjan-bridges";
import tarjanScc from "./algo/graph/tarjan-scc";
import topologicalSortDfs from "./algo/graph/topological-sort-dfs";
import topologicalSortKahn from "./algo/graph/topological-sort-kahn";

// graph additions.
import iterativeDeepeningDfs from "./algo/graph/iterative-deepening-dfs";
import bipartiteCheckTwoColoring from "./algo/graph/bipartite-check-two-coloring";
import connectedComponentsUnionFind from "./algo/graph/connected-components-union-find";
import biconnectedComponentsHopcroftTarjan from "./algo/graph/biconnected-components-hopcroft-tarjan";
import twoSatImplicationGraph from "./algo/graph/two-sat-implication-graph";
import sccCondensationGraph from "./algo/graph/scc-condensation-graph";
import hamiltonianCycleBacktracking from "./algo/graph/hamiltonian-cycle-backtracking";
import greedyColoringWelshPowell from "./algo/graph/greedy-coloring-welsh-powell";
import dsaturColoring from "./algo/graph/dsatur-coloring";
import bronKerboschMaximalCliques from "./algo/graph/bron-kerbosch-maximal-cliques";
import greedyMaximalIndependentSet from "./algo/graph/greedy-maximal-independent-set";
import kCoreDecomposition from "./algo/graph/k-core-decomposition";
import triangleCounting from "./algo/graph/triangle-counting";
import betweennessCentralityBrandes from "./algo/graph/betweenness-centrality-brandes";
import closenessCentrality from "./algo/graph/closeness-centrality";
import pagerankPowerIteration from "./algo/graph/pagerank-power-iteration";
import hitsHubsAuthorities from "./algo/graph/hits-hubs-authorities";
import labelPropagationCommunities from "./algo/graph/label-propagation-communities";
import louvainCommunityDetection from "./algo/graph/louvain-community-detection";
import girvanNewmanEdgeBetweenness from "./algo/graph/girvan-newman-edge-betweenness";
import dominatorsLengauerTarjan from "./algo/graph/dominators-lengauer-tarjan";
import earDecomposition from "./algo/graph/ear-decomposition";
import vf2Isomorphism from "./algo/graph/vf2-isomorphism";
import weisfeilerLemanRefinement from "./algo/graph/weisfeiler-leman-refinement";
import transitiveClosure from "./algo/graph/transitive-closure";
import transitiveReduction from "./algo/graph/transitive-reduction";
import degeneracyOrdering from "./algo/graph/degeneracy-ordering";
import shortestCycleGirthBfs from "./algo/graph/shortest-cycle-girth-bfs";
import chinesePostmanRouteInspection from "./algo/graph/chinese-postman-route-inspection";
import lineGraphConstruction from "./algo/graph/line-graph-construction";
import dfsTreeEdgeClassification from "./algo/graph/dfs-tree-edge-classification";
import graphCenterPeripheryEccentricity from "./algo/graph/graph-center-periphery-eccentricity";

// path additions.
import dialBucketDijkstra from "./algo/path/dial-bucket-dijkstra";
import zeroOneBfs from "./algo/path/zero-one-bfs";
import bidirectionalDijkstra from "./algo/path/bidirectional-dijkstra";
import yenKShortestPaths from "./algo/path/yen-k-shortest-paths";
import widestPathMaxCapacity from "./algo/path/widest-path-max-capacity";
import minimaxPathMst from "./algo/path/minimax-path-mst";
import dagPathCounting from "./algo/path/dag-path-counting";
import jumpPointSearch from "./algo/path/jump-point-search";
import thetaStarAnyAngle from "./algo/path/theta-star-any-angle";
import contractionHierarchies from "./algo/path/contraction-hierarchies";
import altLandmarkRouting from "./algo/path/alt-landmark-routing";
import multiSourceBfs from "./algo/path/multi-source-bfs";
import goldbergRadzikShortestPath from "./algo/path/goldberg-radzik-shortest-path";
import replacementPaths from "./algo/path/replacement-paths";
import secondShortestPath from "./algo/path/second-shortest-path";
import dStarLiteReplanning from "./algo/path/d-star-lite-replanning";
import paretoBicriteriaShortestPath from "./algo/path/pareto-bicriteria-shortest-path";
import resourceConstrainedShortestPath from "./algo/path/resource-constrained-shortest-path";
import timeDependentFifoShortestPath from "./algo/path/time-dependent-fifo-shortest-path";
import deltaSteppingParallelSssp from "./algo/path/delta-stepping-parallel-sssp";

// mst additions.
import reverseDeleteMst from "./algo/mst/reverse-delete-mst";
import edmondsArborescence from "./algo/mst/edmonds-arborescence";
import minimumBottleneckSpanningTree from "./algo/mst/minimum-bottleneck-spanning-tree";
import mstVerificationTarjan from "./algo/mst/mst-verification-tarjan";
import mstSensitivityAnalysis from "./algo/mst/mst-sensitivity-analysis";
import euclideanMstDelaunay from "./algo/mst/euclidean-mst-delaunay";
import kmbSteinerTreeApproximation from "./algo/mst/kmb-steiner-tree-approximation";
import kargerKleinTarjanRandomizedMst from "./algo/mst/karger-klein-tarjan-randomized-mst";
import matrixTreeTheoremCounting from "./algo/mst/matrix-tree-theorem-counting";
import esauWilliamsCapacitatedMst from "./algo/mst/esau-williams-capacitated-mst";
import minimumDiameterSpanningTree from "./algo/mst/minimum-diameter-spanning-tree";
import degreeConstrainedMstHeuristic from "./algo/mst/degree-constrained-mst-heuristic";
import spanningTreeEnumeration from "./algo/mst/spanning-tree-enumeration";

// flow additions.
import gomoryHuTree from "./algo/flow/gomory-hu-tree";
import stoerWagnerMinCut from "./algo/flow/stoer-wagner-min-cut";
import kargerRandomContraction from "./algo/flow/karger-random-contraction";
import feasibleCirculationDemands from "./algo/flow/feasible-circulation-demands";
import maxClosureDirectedGraph from "./algo/flow/max-closure-directed-graph";
import projectSelectionProblem from "./algo/flow/project-selection-problem";
import baseballElimination from "./algo/flow/baseball-elimination";
import bipartiteBMatching from "./algo/flow/bipartite-b-matching";
import konigMinVertexCover from "./algo/flow/konig-min-vertex-cover";
import dagMinimumPathCover from "./algo/flow/dag-minimum-path-cover";
import suurballeEdgeDisjointPair from "./algo/flow/suurballe-edge-disjoint-pair";
import vertexSplitDisjointPaths from "./algo/flow/vertex-split-disjoint-paths";
import capacityScalingMaxFlow from "./algo/flow/capacity-scaling-max-flow";
import cycleCancelingMinCostFlow from "./algo/flow/cycle-canceling-min-cost-flow";
import transportationProblem from "./algo/flow/transportation-problem";
import weightedBlossomMatching from "./algo/flow/weighted-blossom-matching";
import pseudoflowHochbaum from "./algo/flow/pseudoflow-hochbaum";
import nagamochiIbarakiMinCut from "./algo/flow/nagamochi-ibaraki-min-cut";
import minCutCactus from "./algo/flow/min-cut-cactus";
import maximumDensitySubgraph from "./algo/flow/maximum-density-subgraph";
import networkSimplex from "./algo/flow/network-simplex";
import quickestFlowTimeExpanded from "./algo/flow/quickest-flow-time-expanded";
import onlineBipartiteMatchingRanking from "./algo/flow/online-bipartite-matching-ranking";
import galeShapleyStableMarriage from "./algo/flow/gale-shapley-stable-marriage";

// tree additions.
import dsuOnTree from "./algo/tree/dsu-on-tree";
import virtualTree from "./algo/tree/virtual-tree";
import mosOnTrees from "./algo/tree/mos-on-trees";
import treeVertexCoverDp from "./algo/tree/tree-vertex-cover-dp";
import treeDominatingSetDp from "./algo/tree/tree-dominating-set-dp";
import treeMaximumMatchingDp from "./algo/tree/tree-maximum-matching-dp";
import treeKnapsackDp from "./algo/tree/tree-knapsack-dp";
import treePartitionDp from "./algo/tree/tree-partition-dp";
import treeHashing from "./algo/tree/tree-hashing";
import treeEditDistance from "./algo/tree/tree-edit-distance";
import treePatternMatching from "./algo/tree/tree-pattern-matching";
import pruferEncode from "./algo/tree/prufer-encode";
import pruferDecode from "./algo/tree/prufer-decode";
import treeTraversals from "./algo/tree/tree-traversals";
import morrisTraversal from "./algo/tree/morris-traversal";
import treeReconstruction from "./algo/tree/tree-reconstruction";
import threadedBinaryTree from "./algo/tree/threaded-binary-tree";
import optimalBst from "./algo/tree/optimal-bst";
import treeMaxSubtreeSum from "./algo/tree/tree-max-subtree-sum";
import treeEdgeCoverDp from "./algo/tree/tree-edge-cover-dp";
import treePathCover from "./algo/tree/tree-path-cover";
import treeColoringDp from "./algo/tree/tree-coloring-dp";
import treeKDominatingSet from "./algo/tree/tree-k-dominating-set";
import treeSteinerSubtree from "./algo/tree/tree-steiner-subtree";
import decisionTreeId3 from "./algo/tree/decision-tree-id3";
import expressionTreeEvaluation from "./algo/tree/expression-tree-evaluation";
import treeSerializeDeserialize from "./algo/tree/tree-serialize-deserialize";
import binaryLiftingMaxEdgeQuery from "./algo/tree/binary-lifting-max-edge-query";
import treePerfectMatchingGreedy from "./algo/tree/tree-perfect-matching-greedy";

// game additions.
import kayles from "./algo/game/kayles";
import dawsonsKayles from "./algo/game/dawsons-kayles";
import treblecross from "./algo/game/treblecross";
import chomp from "./algo/game/chomp";
import euclidsGame from "./algo/game/euclids-game";
import fibonacciNim from "./algo/game/fibonacci-nim";
import staircaseNim from "./algo/game/staircase-nim";
import mooresNim from "./algo/game/moores-nim";
import nimble from "./algo/game/nimble";
import greenHackenbushStalk from "./algo/game/green-hackenbush-stalk";
import nodeKayles from "./algo/game/node-kayles";
import cram from "./algo/game/cram";
import snort from "./algo/game/snort";
import col from "./algo/game/col";
import domineering from "./algo/game/domineering";
import geographyGame from "./algo/game/geography-game";
import turningTurtles from "./algo/game/turning-turtles";
import goAtariCapture from "./algo/game/go-atari-capture";
import expectiminimax from "./algo/game/expectiminimax";
import mctsUct from "./algo/game/mcts-uct";
import proofNumberSearch from "./algo/game/proof-number-search";
import retrogradeAnalysis from "./algo/game/retrograde-analysis";
import dotsAndBoxes from "./algo/game/dots-and-boxes";
import sprouts from "./algo/game/sprouts";

// sort additions.
import gnomeSort from "./algo/sort/gnome-sort";
import oddEvenTranspositionSort from "./algo/sort/odd-even-transposition-sort";
import bitonicSort from "./algo/sort/bitonic-sort";
import batcherOddEvenMergeSort from "./algo/sort/batcher-odd-even-merge-sort";
import boseNelsonSortingNetwork from "./algo/sort/bose-nelson-sorting-network";
import shearSort from "./algo/sort/shear-sort";
import columnSort from "./algo/sort/column-sort";
import pancakeSort from "./algo/sort/pancake-sort";
import cycleSort from "./algo/sort/cycle-sort";
import strandSort from "./algo/sort/strand-sort";
import tournamentSort from "./algo/sort/tournament-sort";
import treeSort from "./algo/sort/tree-sort";
import splaySort from "./algo/sort/splay-sort";
import librarySort from "./algo/sort/library-sort";
import blockSort from "./algo/sort/block-sort";
import mergeInsertionSort from "./algo/sort/merge-insertion-sort";
import stoogeSort from "./algo/sort/stooge-sort";
import slowSort from "./algo/sort/slow-sort";
import beadSort from "./algo/sort/bead-sort";
import burstsort from "./algo/sort/burstsort";
import americanFlagSort from "./algo/sort/american-flag-sort";
import pigeonholeSort from "./algo/sort/pigeonhole-sort";
import flashSort from "./algo/sort/flash-sort";
import proxmapSort from "./algo/sort/proxmap-sort";
import samplesort from "./algo/sort/samplesort";
import externalKWayMergeSort from "./algo/sort/external-k-way-merge-sort";
import polyphaseMergeSort from "./algo/sort/polyphase-merge-sort";
import cascadeMergeSort from "./algo/sort/cascade-merge-sort";
import replacementSelectionSort from "./algo/sort/replacement-selection-sort";
import sleepSort from "./algo/sort/sleep-sort";
import circleSort from "./algo/sort/circle-sort";
import wiggleSort from "./algo/sort/wiggle-sort";
import loserTreeMergeSort from "./algo/sort/loser-tree-merge-sort";
import aksSortingNetwork from "./algo/sort/aks-sorting-network";
import stackPermutationSort from "./algo/sort/stack-permutation-sort";
import dequeSortablePermutations from "./algo/sort/deque-sortable-permutations";
import genomeReversalSort from "./algo/sort/genome-reversal-sort";
import cubeSort from "./algo/sort/cube-sort";
import genomeTranspositionSort from "./algo/sort/genome-transposition-sort";
import weakHeapSort from "./algo/sort/weak-heap-sort";
import naturalMergeSort from "./algo/sort/natural-merge-sort";
import bidirectionalSelectionSort from "./algo/sort/bidirectional-selection-sort";

// search additions.
import fibonacciSearch from "./algo/search/fibonacci-search";
import rotatedArraySearch from "./algo/search/rotated-array-search";
import bitonicArraySearch from "./algo/search/bitonic-array-search";
import peakFinding1d from "./algo/search/peak-finding-1d";
import peakFinding2d from "./algo/search/peak-finding-2d";
import saddlebackSearch from "./algo/search/saddleback-search";
import quickselect from "./algo/search/quickselect";
import medianOfMediansSelect from "./algo/search/median-of-medians-select";
import sqrtDecompositionSearch from "./algo/search/sqrt-decomposition-search";
import fractionalCascading from "./algo/search/fractional-cascading";
import greedyBestFirstSearch from "./algo/search/greedy-best-first-search";
import beamSearch from "./algo/search/beam-search";
import idaStarSearch from "./algo/search/ida-star-search";
import smaStarSearch from "./algo/search/sma-star-search";
import rbfsSearch from "./algo/search/rbfs-search";
import uniformCostSearch from "./algo/search/uniform-cost-search";
import branchAndBoundSearch from "./algo/search/branch-and-bound-search";
import backtrackingCspSearch from "./algo/search/backtracking-csp-search";
import ac3ArcConsistency from "./algo/search/ac3-arc-consistency";
import minConflictsSearch from "./algo/search/min-conflicts-search";
import dpllSatSearch from "./algo/search/dpll-sat-search";
import walksatSearch from "./algo/search/walksat-search";
import majorityVoteSearch from "./algo/search/majority-vote-search";
import floydDuplicateSearch from "./algo/search/floyd-duplicate-search";
import firstMissingPositiveSearch from "./algo/search/first-missing-positive-search";
import medianOfTwoSortedArrays from "./algo/search/median-of-two-sorted-arrays";
import kthInSortedMatrixSearch from "./algo/search/kth-in-sorted-matrix-search";
import nearlySortedArraySearch from "./algo/search/nearly-sorted-array-search";
import twoPointerPairSumSearch from "./algo/search/two-pointer-pair-sum-search";
import sublistSearch from "./algo/search/sublist-search";

// string additions.
import sundayQuickShift from "./algo/string/sunday-quick-shift";
import horspoolSearch from "./algo/string/horspool-search";
import shiftOrBitap from "./algo/string/shift-or-bitap";
import myersBitparallelApprox from "./algo/string/myers-bitparallel-approx";
import wuManberSearch from "./algo/string/wu-manber-search";
import bndmDawgMatching from "./algo/string/bndm-dawg-matching";
import twoWayStringMatching from "./algo/string/two-way-string-matching";
import suffixArraySearch from "./algo/string/suffix-array-search";
import lcpRmqQueries from "./algo/string/lcp-rmq-queries";
import shortestUniqueSubstring from "./algo/string/shortest-unique-substring";
import distinctSubstringsCount from "./algo/string/distinct-substrings-count";
import runsViaLyndon from "./algo/string/runs-via-lyndon";
import palindromicFactorization from "./algo/string/palindromic-factorization";
import needlemanWunschAlignment from "./algo/string/needleman-wunsch-alignment";
import smithWatermanAlignment from "./algo/string/smith-waterman-alignment";
import hirschbergAlignment from "./algo/string/hirschberg-alignment";
import bandedDpApproxMatching from "./algo/string/banded-dp-approx-matching";
import myersDiffOnd from "./algo/string/myers-diff-ond";
import burrowsWheelerTransform from "./algo/string/burrows-wheeler-transform";
import lfMappingInversion from "./algo/string/lf-mapping-inversion";
import fmIndexSearch from "./algo/string/fm-index-search";
import moveToFrontTransform from "./algo/string/move-to-front-transform";
import cykParsing from "./algo/string/cyk-parsing";
import earleyParsing from "./algo/string/earley-parsing";
import ll1TableParsing from "./algo/string/ll1-table-parsing";
import lr0ShiftReduceParsing from "./algo/string/lr0-shift-reduce-parsing";
import thompsonNfaConstruction from "./algo/string/thompson-nfa-construction";
import subsetConstruction from "./algo/string/subset-construction";
import hopcroftDfaMinimization from "./algo/string/hopcroft-dfa-minimization";
import samOccurrenceQueries from "./algo/string/sam-occurrence-queries";
import bomFactorOracleMatching from "./algo/string/bom-factor-oracle-matching";
import setHorspoolSearch from "./algo/string/set-horspool-search";
import jaroWinklerSimilarity from "./algo/string/jaro-winkler-similarity";
import soundexPhoneticCoding from "./algo/string/soundex-phonetic-coding";
import porterStemmer from "./algo/string/porter-stemmer";
import shuntingYardParse from "./algo/string/shunting-yard-parse";
import dotPlotAlignment from "./algo/string/dot-plot-alignment";
import metaphonePhoneticCoding from "./algo/string/metaphone-phonetic-coding";
import levenshteinAutomatonSearch from "./algo/string/levenshtein-automaton-search";
import qGramFilterSearch from "./algo/string/q-gram-filter-search";
import bytePairEncodingTokenization from "./algo/string/byte-pair-encoding-tokenization";
import patienceDiff from "./algo/string/patience-diff";

// special additions.
import geneticAlgorithm from "./algo/special/genetic-algorithm";
import particleSwarmOptimization from "./algo/special/particle-swarm-optimization";
import antColonyOptimization from "./algo/special/ant-colony-optimization";
import tabuSearch from "./algo/special/tabu-search";
import gradientDescent1d from "./algo/special/gradient-descent-1d";
import newtonRaphsonRoot from "./algo/special/newton-raphson-root";
import bisectionMethod from "./algo/special/bisection-method";
import goldenSectionSearch from "./algo/special/golden-section-search";
import nelderMeadSimplex from "./algo/special/nelder-mead-simplex";
import freivaldsCheck from "./algo/special/freivalds-check";
import schwartzZippelIdentity from "./algo/special/schwartz-zippel-identity";
import diffieHellmanExchange from "./algo/special/diffie-hellman-exchange";
import secretaryProblem from "./algo/special/secretary-problem";
import banditUcb from "./algo/special/bandit-ucb";
import simplexMethodLp from "./algo/special/simplex-method-lp";
import gibbsSampling from "./algo/special/gibbs-sampling";
import reservoirSampling from "./algo/special/reservoir-sampling";
import morrisCounter from "./algo/special/morris-counter";
import hyperloglog from "./algo/special/hyperloglog";
import misraGriesSummary from "./algo/special/misra-gries-summary";
import greenwaldKhannaQuantiles from "./algo/special/greenwald-khanna-quantiles";
import minhashLsh from "./algo/special/minhash-lsh";
import consistentHashing from "./algo/special/consistent-hashing";
import lamportClock from "./algo/special/lamport-clock";
import vectorClock from "./algo/special/vector-clock";
import chordDhtLookup from "./algo/special/chord-dht-lookup";
import merkleTreeProof from "./algo/special/merkle-tree-proof";
import gossipProtocol from "./algo/special/gossip-protocol";
import pagingAlgorithmsRace from "./algo/special/paging-algorithms-race";
import lz77Coding from "./algo/special/lz77-coding";
import lz78Coding from "./algo/special/lz78-coding";
import lzwCoding from "./algo/special/lzw-coding";
import arithmeticCoding from "./algo/special/arithmetic-coding";
import eliasGammaCoding from "./algo/special/elias-gamma-coding";
import skylineDivideConquer from "./algo/special/skyline-divide-conquer";

// dp additions.
import coinChangeCount from "./algo/dp/coin-change-count";
import coinChangeMinCoins from "./algo/dp/coin-change-min-coins";
import rodCutting from "./algo/dp/rod-cutting";
import eggDrop from "./algo/dp/egg-drop";
import palindromePartitioningMinCuts from "./algo/dp/palindrome-partitioning-min-cuts";
import burstBalloons from "./algo/dp/burst-balloons";
import gridPathsCountWithObstacles from "./algo/dp/grid-paths-count-with-obstacles";
import minPathSumGrid from "./algo/dp/min-path-sum-grid";
import dungeonGame from "./algo/dp/dungeon-game";
import distinctSubsequencesCount from "./algo/dp/distinct-subsequences-count";
import longestPalindromicSubseq from "./algo/dp/longest-palindromic-subseq";
import wildcardMatching from "./algo/dp/wildcard-matching";
import regexMatchingDp from "./algo/dp/regex-matching-dp";
import interleavingString from "./algo/dp/interleaving-string";
import stockIIITwoTransactions from "./algo/dp/stock-III-two-transactions";
import stockWithCooldown from "./algo/dp/stock-with-cooldown";
import stockWithTransactionFee from "./algo/dp/stock-with-transaction-fee";
import houseRobberLinear from "./algo/dp/house-robber-linear";
import houseRobberCircular from "./algo/dp/house-robber-circular";
import jumpGameMinJumps from "./algo/dp/jump-game-min-jumps";
import assignmentBitmaskDp from "./algo/dp/assignment-bitmask-dp";
import profilePlugDpBrokenProfile from "./algo/dp/profile-plug-dp-broken-profile";
import sosDpSumOverSubsets from "./algo/dp/sos-dp-sum-over-subsets";
import convexHullTrickStatic from "./algo/dp/convex-hull-trick-static";
import liChaoSegmentTreeDp from "./algo/dp/li-chao-segment-tree-dp";
import optimalGameStrategyPickEnds from "./algo/dp/optimal-game-strategy-pick-ends";
import booleanParenthesization from "./algo/dp/boolean-parenthesization";
import wordBreakCount from "./algo/dp/word-break-count";
import catalanDpCounting from "./algo/dp/catalan-dp-counting";
import derangementsDp from "./algo/dp/derangements-dp";
import tilingDpDominoTromino from "./algo/dp/tiling-dp-domino-tromino";
import decodeWays from "./algo/dp/decode-ways";
import longestArithmeticSubsequence from "./algo/dp/longest-arithmetic-subsequence";
import boxStacking from "./algo/dp/box-stacking";
import weightedIntervalScheduling from "./algo/dp/weighted-interval-scheduling";
import activitySelectionGreedy from "./algo/dp/activity-selection-greedy";
import longestPalindromicSubstring from "./algo/dp/longest-palindromic-substring";
import longestBitonicSubsequence from "./algo/dp/longest-bitonic-subsequence";
import maximalSquare from "./algo/dp/maximal-square";
import maximalRectangleBinaryMatrix from "./algo/dp/maximal-rectangle-binary-matrix";
import friendsPairingCount from "./algo/dp/friends-pairing-count";
import longestValidParenthesesDp from "./algo/dp/longest-valid-parentheses-dp";

// math additions.
import trialDivisionFactorization from "./algo/math/trial-division-factorization";
import fermatFactorization from "./algo/math/fermat-factorization";
import solovayStrassenTest from "./algo/math/solovay-strassen-test";
import lucasLehmerMersenne from "./algo/math/lucas-lehmer-mersenne";
import pohligHellmanDiscreteLog from "./algo/math/pohlig-hellman-discrete-log";
import pollardRhoDiscreteLog from "./algo/math/pollard-rho-discrete-log";
import montgomeryReduction from "./algo/math/montgomery-reduction";
import ncrPrecomputeFactorials from "./algo/math/ncr-precompute-factorials";
import karatsubaMultiplication from "./algo/math/karatsuba-multiplication";
import polynomialLongDivision from "./algo/math/polynomial-long-division";
import continuedFractionsConvergents from "./algo/math/continued-fractions-convergents";
import sternBrocotTree from "./algo/math/stern-brocot-tree";
import binaryGcdStein from "./algo/math/binary-gcd-stein";
import primeCountingMeisselLehmer from "./algo/math/prime-counting-meissel-lehmer";
import segmentedSieve from "./algo/math/segmented-sieve";
import sieveOfAtkin from "./algo/math/sieve-of-atkin";
import primitiveRootSearch from "./algo/math/primitive-root-search";
import multiplicativeOrderFinding from "./algo/math/multiplicative-order-finding";
import luDecomposition from "./algo/math/lu-decomposition";
import modularGaussianEliminationModP from "./algo/math/modular-gaussian-elimination-mod-p";
import ellipticCurvePointAddition from "./algo/math/elliptic-curve-point-addition";
import shamirSecretSharing from "./algo/math/shamir-secret-sharing";
import lagrangeInterpolation from "./algo/math/lagrange-interpolation";
import grayCodeGeneration from "./algo/math/gray-code-generation";
import josephusProblem from "./algo/math/josephus-problem";
import divisorSieveSigma from "./algo/math/divisor-sieve-sigma";
import henselLiftingRoot from "./algo/math/hensel-lifting-root";
import pollardPMinus1 from "./algo/math/pollard-p-minus-1";
import legendreSymbolEulerCriterion from "./algo/math/legendre-symbol-euler-criterion";
import jacobiSymbol from "./algo/math/jacobi-symbol";
import wilsonTheoremPrimeTest from "./algo/math/wilson-theorem-prime-test";
import inclusionExclusionCounting from "./algo/math/inclusion-exclusion-counting";
import linearCongruenceSolver from "./algo/math/linear-congruence-solver";
import additionChainBrauerStar from "./algo/math/addition-chain-brauer-star";
import lucasSequencesLehmer from "./algo/math/lucas-sequences-lehmer";
import sieveOfSundaram from "./algo/math/sieve-of-sundaram";
import factorialPrimeExponentLegendre from "./algo/math/factorial-prime-exponent-legendre";
import integerSqrtNewton from "./algo/math/integer-sqrt-newton";
import goldbachPartitionsSieve from "./algo/math/goldbach-partitions-sieve";
import twinPrimeSieve from "./algo/math/twin-prime-sieve";
import bertrandPostulateCheck from "./algo/math/bertrand-postulate-check";
import modularTetrationTowerEuler from "./algo/math/modular-tetration-tower-euler";
import linearDiophantineTwoVar from "./algo/math/linear-diophantine-two-var";
import hammingCodeEncodeDecode from "./algo/math/hamming-code-encode-decode";
import bailliePswPrimality from "./algo/math/baillie-psw-primality";
import carmichaelKorseltTest from "./algo/math/carmichael-korselt-test";
import elgamalEncryptionToy from "./algo/math/elgamal-encryption-toy";
import fareySequence from "./algo/math/farey-sequence";
import evenPerfectNumbersEuler from "./algo/math/even-perfect-numbers-euler";
import permutationRankFactoradic from "./algo/math/permutation-rank-factoradic";

// geo additions.
import delaunayTriangulationIncremental from "./algo/geo/delaunay-triangulation-incremental";
import voronoiDiagramFortune from "./algo/geo/voronoi-diagram-fortune";
import polygonTriangulationEarClipping from "./algo/geo/polygon-triangulation-ear-clipping";
import polygonCentroid from "./algo/geo/polygon-centroid";
import convexLayersOnionPeeling from "./algo/geo/convex-layers-onion-peeling";
import minEnclosingRectangleRotating from "./algo/geo/min-enclosing-rectangle-rotating";
import kernelOfPolygon from "./algo/geo/kernel-of-polygon";
import circleCircleIntersectionPoints from "./algo/geo/circle-circle-intersection-points";
import lineCircleIntersectionPoints from "./algo/geo/line-circle-intersection-points";
import pickTheoremLatticePoints from "./algo/geo/pick-theorem-lattice-points";
import rectangleUnionKleeMeasureSweep from "./algo/geo/rectangle-union-klee-measure-sweep";
import alphaShapes from "./algo/geo/alpha-shapes";
import kMeansLloyd from "./algo/geo/k-means-lloyd";
import dbscanClustering from "./algo/geo/dbscan-clustering";
import pointLineDualityTransform from "./algo/geo/point-line-duality-transform";
import visibilityPolygon from "./algo/geo/visibility-polygon";
import artGalleryGuardFisk from "./algo/geo/art-gallery-guard-fisk";
import shortestPathInPolygonFunnel from "./algo/geo/shortest-path-in-polygon-funnel";
import lineArrangementIncremental from "./algo/geo/line-arrangement-incremental";
import incremental2dLinearProgramming from "./algo/geo/incremental-2d-linear-programming";
import circumcenterCircleThrough3Points from "./algo/geo/circumcenter-circle-through-3-points";
import gabrielGraphProximity from "./algo/geo/gabriel-graph-proximity";
import hierarchicalAgglomerativeClustering from "./algo/geo/hierarchical-agglomerative-clustering";
import latticePointsGaussCircle from "./algo/geo/lattice-points-gauss-circle";
import bresenhamLineRasterization from "./algo/geo/bresenham-line-rasterization";
import midpointCircleRasterization from "./algo/geo/midpoint-circle-rasterization";
import sutherlandHodgmanPolygonClipping from "./algo/geo/sutherland-hodgman-polygon-clipping";
import cohenSutherlandLineClipping from "./algo/geo/cohen-sutherland-line-clipping";
import pointSegmentDistance from "./algo/geo/point-segment-distance";
import trapezoidalMapPointLocation from "./algo/geo/trapezoidal-map-point-location";
import douglasPeuckerPolylineSimplification from "./algo/geo/douglas-peucker-polyline-simplification";
import marchingSquaresIsocontour from "./algo/geo/marching-squares-isocontour";
import largestEmptyCircleVoronoi from "./algo/geo/largest-empty-circle-voronoi";
import circleUnionAreaSweep from "./algo/geo/circle-union-area-sweep";
import gjkConvexPolygonDistance from "./algo/geo/gjk-convex-polygon-distance";
import hilbertCurvePointOrdering from "./algo/geo/hilbert-curve-point-ordering";
import poissonDiskSampling from "./algo/geo/poisson-disk-sampling";
import skylineProblemSweep from "./algo/geo/skyline-problem-sweep";
import maxCollinearPointsLineThroughMost from "./algo/geo/max-collinear-points-line-through-most";
import christofidesEuclideanTsp from "./algo/geo/christofides-euclidean-tsp";
import pointInConvexPolygonBinary from "./algo/geo/point-in-convex-polygon-binary";
import convexPolygonIntersection from "./algo/geo/convex-polygon-intersection";

// ds additions.
import aaTree from "./algo/ds/aa-tree";
import scapegoatTree from "./algo/ds/scapegoat-tree";
import weightBalancedTree from "./algo/ds/weight-balanced-tree";
import zipTree from "./algo/ds/zip-tree";
import tangoTree from "./algo/ds/tango-tree";
import orderStatisticTree from "./algo/ds/order-statistic-tree";
import intervalTree from "./algo/ds/interval-tree";
import rangeTree2d from "./algo/ds/range-tree-2d";
import cartesianTree from "./algo/ds/cartesian-tree";
import rope from "./algo/ds/rope";
import gapBuffer from "./algo/ds/gap-buffer";
import pieceTable from "./algo/ds/piece-table";
import hashedArrayTree from "./algo/ds/hashed-array-tree";
import tieredVector from "./algo/ds/tiered-vector";
import sparseSet from "./algo/ds/sparse-set";
import bitset from "./algo/ds/bitset";
import roaringBitmap from "./algo/ds/roaring-bitmap";
import cuckooHashing from "./algo/ds/cuckoo-hashing";
import robinHoodHashing from "./algo/ds/robin-hood-hashing";
import hopscotchHashing from "./algo/ds/hopscotch-hashing";
import coalescedHashing from "./algo/ds/coalesced-hashing";
import fksPerfectHashing from "./algo/ds/fks-perfect-hashing";
import extendibleHashing from "./algo/ds/extendible-hashing";
import linearHashing from "./algo/ds/linear-hashing";
import rendezvousHashing from "./algo/ds/rendezvous-hashing";
import countingBloomFilter from "./algo/ds/counting-bloom-filter";
import cuckooFilter from "./algo/ds/cuckoo-filter";
import quotientFilter from "./algo/ds/quotient-filter";
import xorFilter from "./algo/ds/xor-filter";
import minhashSketch from "./algo/ds/minhash-sketch";
import tDigest from "./algo/ds/t-digest";
import kllSketch from "./algo/ds/kll-sketch";
import sparseTable from "./algo/ds/sparse-table";
import disjointSparseTable from "./algo/ds/disjoint-sparse-table";
import fenwickTree2d from "./algo/ds/fenwick-tree-2d";
import mergeSortTree from "./algo/ds/merge-sort-tree";
import waveletTree from "./algo/ds/wavelet-tree";
import waveletMatrix from "./algo/ds/wavelet-matrix";
import sqrtDecompositionArray from "./algo/ds/sqrt-decomposition-array";
import quadtree from "./algo/ds/quadtree";
import octree from "./algo/ds/octree";
import kDTree from "./algo/ds/k-d-tree";
import ballTree from "./algo/ds/ball-tree";
import rTree from "./algo/ds/r-tree";
import vpTree from "./algo/ds/vp-tree";
import bkTree from "./algo/ds/bk-tree";
import coverTree from "./algo/ds/cover-tree";
import mTree from "./algo/ds/m-tree";
import bspTree from "./algo/ds/bsp-tree";
import gridFile from "./algo/ds/grid-file";
import kdbTree from "./algo/ds/kdb-tree";
import ubTree from "./algo/ds/ub-tree";
import patriciaTrie from "./algo/ds/patricia-trie";
import binaryTrie from "./algo/ds/binary-trie";
import adaptiveRadixTree from "./algo/ds/adaptive-radix-tree";
import hamt from "./algo/ds/hamt";
import burstTrie from "./algo/ds/burst-trie";
import doubleArrayTrie from "./algo/ds/double-array-trie";
import xFastTrie from "./algo/ds/x-fast-trie";
import yFastTrie from "./algo/ds/y-fast-trie";
import vanEmdeBoasTree from "./algo/ds/van-emde-boas-tree";
import concurrentTrie from "./algo/ds/concurrent-trie";
import lsmTree from "./algo/ds/lsm-tree";
import fractalTree from "./algo/ds/fractal-tree";
import cacheObliviousBtree from "./algo/ds/cache-oblivious-btree";
import tTree from "./algo/ds/t-tree";
import orthogonalList from "./algo/ds/orthogonal-list";
import doublyConnectedEdgeList from "./algo/ds/doubly-connected-edge-list";
import adjacencySet from "./algo/ds/adjacency-set";
import linkCutTree from "./algo/ds/link-cut-tree";
import eulerTourTree from "./algo/ds/euler-tour-tree";
import topTree from "./algo/ds/top-tree";
import hollowHeap from "./algo/ds/hollow-heap";
import softHeap from "./algo/ds/soft-heap";
import minMaxHeap from "./algo/ds/min-max-heap";
import intervalHeap from "./algo/ds/interval-heap";
import weakHeap from "./algo/ds/weak-heap";
import twoThreeHeap from "./algo/ds/two-three-heap";
import radixHeap from "./algo/ds/radix-heap";
import bucketHeap from "./algo/ds/bucket-heap";
import bHeapExternal from "./algo/ds/b-heap-external";
import funnelHeap from "./algo/ds/funnel-heap";
import quakeHeap from "./algo/ds/quake-heap";
import beap from "./algo/ds/beap";
import brodalHeap from "./algo/ds/brodal-heap";
import calendarQueue from "./algo/ds/calendar-queue";
import minQueue from "./algo/ds/min-queue";
import steque from "./algo/ds/steque";
import twoStackQueue from "./algo/ds/two-stack-queue";
import twoQueueStack from "./algo/ds/two-queue-stack";
import lockFreeStack from "./algo/ds/lock-free-stack";
import lruCache from "./algo/ds/lru-cache";
import lfuCache from "./algo/ds/lfu-cache";
import arcCache from "./algo/ds/arc-cache";
import clockCache from "./algo/ds/clock-cache";
import persistentStack from "./algo/ds/persistent-stack";
import persistentArray from "./algo/ds/persistent-array";
import persistentBst from "./algo/ds/persistent-bst";
import bankersQueue from "./algo/ds/bankers-queue";
import skewBinaryList from "./algo/ds/skew-binary-list";
import vlist from "./algo/ds/vlist";
import fingerTree from "./algo/ds/finger-tree";
import rankSelectBitvector from "./algo/ds/rank-select-bitvector";
import loudsTrie from "./algo/ds/louds-trie";
import buddyAllocator from "./algo/ds/buddy-allocator";
import slabAllocator from "./algo/ds/slab-allocator";
import freeListAllocator from "./algo/ds/free-list-allocator";
import arenaAllocator from "./algo/ds/arena-allocator";
import dsuRollback from "./algo/ds/dsu-rollback";
import unionFindDeletions from "./algo/ds/union-find-deletions";
import twoThreeTree from "./algo/ds/two-three-tree";
import lockFreeQueueMichaelScott from "./algo/ds/lock-free-queue-michael-scott";
import workStealingDequeChaseLev from "./algo/ds/work-stealing-deque-chase-lev";
import countSketch from "./algo/ds/count-sketch";
register(binarySearchIterative);
register(binarySearchLowerBound);
register(binarySearchRecursive);
register(binarySearchUpperBound);
register(bfs);
register(bidirectionalBfs);
register(dfsIterative);
register(dfsRecursive);
register(aStar);
register(bellmanFord);
register(blossom);
register(dijkstraFibonacci);
register(dijkstraHeap);
register(dijkstraMatrix);
register(floydWarshall);
register(johnson);
register(karpMinimumMeanCycle);
register(kruskal);
register(boruvka);
register(primHeap);
register(primMatrix);
register(secondBestMst);
register(fordFulkerson);
register(edmondsKarp);
register(minCut);
register(minCostMaxFlow);
register(boykovKolmogorov);
register(costScaling);
register(dinic);
register(pushRelabel);
register(shortestPathDag);
register(spfa);
register(treeCenter);
register(treeDiameter);
register(treeEulerTour);
register(treeIsomorphism);
register(lcaBinaryLifting);
register(lcaEulerSparse);
register(lcaTarjanOffline);
register(centroidDecomposition);
register(heavyLightDecomposition);
register(rerootingDp);
register(knuthMorrisPratt);
register(zAlgorithm);
register(rabinKarpSingle);
register(rabinKarpDouble);
register(manacher);
register(suffixArrayDoubling);
register(suffixArrayDc3);
register(lcpKasai);
register(suffixAutomaton);
register(suffixTreeUkkonen);
register(ahoCorasick);
register(eertree);
register(boyerMoore);
register(boothMinimalRotation);
register(duvalLyndon);
register(longestCommonSubstring);
register(longestCommonPrefixDp);
register(zAlgorithmOnTree);
register(rollingHash2d);
register(prefixFunctionAuto);
register(euclidGcd);
register(extendedEuclid);
register(binaryExponentiation);
register(matrixExponentiation);
register(sieveEratosthenes);
register(linearSieve);
register(millerRabin);
register(pollardRho);
register(fermatLittle);
register(eulerTotient);
register(modularInverse);
register(crtCoprime);
register(crtGeneralized);
register(lucasTheorem);
register(mobiusInversion);
register(gaussianElimination);
register(gaussianEliminationGf2);
register(bareissFractionFree);
register(tonelliShanks);
register(babyStepGiantStep);
register(discreteRoot);
register(fftCooleyTukey);
register(ntt);
register(polynomialInversion);
register(polynomialLogExp);
register(lis);
register(lcs);
register(shortestCommonSupersequence);
register(editDistance);
register(knapsack01);
register(knapsackComplete);
register(knapsackMultiple);
register(subsetSum);
register(bitmaskTsp);
register(digitDp);
register(intervalMatrixChain);
register(treeDpIndependentSet);
register(treeDpRerooting);
register(dagShortestDp);
register(dagLongestDp);
register(countingDp);
register(probabilityDp);
register(divideConquerDp);
register(knuthOptimization);
register(aliensTrick);
register(monotonicQueueDp);
register(nim);
register(misereNim);
register(spragueGrundy);
register(minimax);
register(alphaBeta);
register(wythoff);
register(dotCrossProduct);
register(segmentIntersection);
register(sweepLineSegmentIntersection);
register(pointInPolygonRay);
register(pointInPolygonWinding);
register(convexHullGraham);
register(convexHullMonotone);
register(convexHullJarvis);
register(closestPairOfPoints);
register(rotatingCalipers);
register(polygonAreaShoelace);
register(minEnclosingCircleWelzl);
register(halfPlaneIntersection);
register(staticArray);
register(dynamicArray);
register(singlyLinkedList);
register(doublyLinkedList);
register(circularLinkedList);
register(skipList);
register(stackArray);
register(stackLinked);
register(queueArray);
register(queueLinked);
register(deque);
register(priorityQueue);
register(monotonicQueue);
register(monotonicStack);
register(minStack);
register(unrolledLinkedList);
register(xorLinkedList);
register(sortedLinkedList);
register(concurrentQueue);
register(cyclicBuffer);
register(binaryTree);
register(bst);
register(avlTree);
register(redBlackTree);
register(splayTree);
register(treap);
register(bTree);
register(bPlusTree);
register(trie);
register(ternarySearchTrie);
register(suffixTrie);
register(fenwickTree);
register(fenwickTreeRange);
register(segmentTreeRecursive);
register(segmentTreeIterative);
register(segmentTreeLazy);
register(persistentSegmentTree);
register(dynamicSegmentTree);
register(binaryHeap);
register(fibonacciHeap);
register(pairingHeap);
register(leftistHeap);
register(skewHeap);
register(binomialHeap);
register(daryHeap);
register(adjacencyMatrix);
register(adjacencyList);
register(edgeList);
register(incidenceMatrix);
register(csr);
register(hashMapChaining);
register(hashMapOpen);
register(linkedHashMap);
register(hashSet);
register(dsu);
register(persistentDsu);
register(kadane);
register(kadane2d);
register(runLengthEncoding);
register(huffmanCoding);
register(bloomFilter);
register(countMinSketch);
register(simulatedAnnealing);
register(hillClimbing);
register(monteCarlo);
register(lasVegas);
register(exponentialSearch);
register(floodFillBfs);
register(floodFillDfs);
register(gabowScc);
register(hierholzerEulerian);
register(hopcroftKarp);
register(hungarian);
register(kosarajuScc);
register(lexicographicBfs);
register(tarjanArticulationPoints);
register(tarjanBridges);
register(tarjanScc);
register(topologicalSortDfs);
register(topologicalSortKahn);
register(interpolationSearch);
register(jumpSearch);
register(ternarySearch);
register(bubbleSort);
register(bucketSort);
register(cocktailShakerSort);
register(combSort);
register(countingSort);
register(heapSort);
register(insertionSort);
register(introsort);
register(mergeSortBottomUp);
register(mergeSortTopDown);
register(monkeySort);
register(patienceSort);
register(quickSort3Way);
register(quickSortHoare);
register(quickSortLomuto);
register(radixSortLsd);
register(radixSortMsd);
register(selectionSort);
register(shellSort);
register(smoothSort);
register(timSort);
register(linearSearch);
register(iterativeDeepeningDfs);
register(bipartiteCheckTwoColoring);
register(connectedComponentsUnionFind);
register(biconnectedComponentsHopcroftTarjan);
register(twoSatImplicationGraph);
register(sccCondensationGraph);
register(hamiltonianCycleBacktracking);
register(greedyColoringWelshPowell);
register(dsaturColoring);
register(bronKerboschMaximalCliques);
register(greedyMaximalIndependentSet);
register(kCoreDecomposition);
register(triangleCounting);
register(betweennessCentralityBrandes);
register(closenessCentrality);
register(pagerankPowerIteration);
register(hitsHubsAuthorities);
register(labelPropagationCommunities);
register(louvainCommunityDetection);
register(girvanNewmanEdgeBetweenness);
register(dominatorsLengauerTarjan);
register(earDecomposition);
register(vf2Isomorphism);
register(weisfeilerLemanRefinement);
register(transitiveClosure);
register(transitiveReduction);
register(degeneracyOrdering);
register(shortestCycleGirthBfs);
register(chinesePostmanRouteInspection);
register(lineGraphConstruction);
register(dfsTreeEdgeClassification);
register(graphCenterPeripheryEccentricity);
register(dialBucketDijkstra);
register(zeroOneBfs);
register(bidirectionalDijkstra);
register(yenKShortestPaths);
register(widestPathMaxCapacity);
register(minimaxPathMst);
register(dagPathCounting);
register(jumpPointSearch);
register(thetaStarAnyAngle);
register(contractionHierarchies);
register(altLandmarkRouting);
register(multiSourceBfs);
register(goldbergRadzikShortestPath);
register(replacementPaths);
register(secondShortestPath);
register(dStarLiteReplanning);
register(paretoBicriteriaShortestPath);
register(resourceConstrainedShortestPath);
register(timeDependentFifoShortestPath);
register(deltaSteppingParallelSssp);
register(reverseDeleteMst);
register(edmondsArborescence);
register(minimumBottleneckSpanningTree);
register(mstVerificationTarjan);
register(mstSensitivityAnalysis);
register(euclideanMstDelaunay);
register(kmbSteinerTreeApproximation);
register(kargerKleinTarjanRandomizedMst);
register(matrixTreeTheoremCounting);
register(esauWilliamsCapacitatedMst);
register(minimumDiameterSpanningTree);
register(degreeConstrainedMstHeuristic);
register(spanningTreeEnumeration);
register(gomoryHuTree);
register(stoerWagnerMinCut);
register(kargerRandomContraction);
register(feasibleCirculationDemands);
register(maxClosureDirectedGraph);
register(projectSelectionProblem);
register(baseballElimination);
register(bipartiteBMatching);
register(konigMinVertexCover);
register(dagMinimumPathCover);
register(suurballeEdgeDisjointPair);
register(vertexSplitDisjointPaths);
register(capacityScalingMaxFlow);
register(cycleCancelingMinCostFlow);
register(transportationProblem);
register(weightedBlossomMatching);
register(pseudoflowHochbaum);
register(nagamochiIbarakiMinCut);
register(minCutCactus);
register(maximumDensitySubgraph);
register(networkSimplex);
register(quickestFlowTimeExpanded);
register(onlineBipartiteMatchingRanking);
register(galeShapleyStableMarriage);
register(dsuOnTree);
register(virtualTree);
register(mosOnTrees);
register(treeVertexCoverDp);
register(treeDominatingSetDp);
register(treeMaximumMatchingDp);
register(treeKnapsackDp);
register(treePartitionDp);
register(treeHashing);
register(treeEditDistance);
register(treePatternMatching);
register(pruferEncode);
register(pruferDecode);
register(treeTraversals);
register(morrisTraversal);
register(treeReconstruction);
register(threadedBinaryTree);
register(optimalBst);
register(treeMaxSubtreeSum);
register(treeEdgeCoverDp);
register(treePathCover);
register(treeColoringDp);
register(treeKDominatingSet);
register(treeSteinerSubtree);
register(decisionTreeId3);
register(expressionTreeEvaluation);
register(treeSerializeDeserialize);
register(binaryLiftingMaxEdgeQuery);
register(treePerfectMatchingGreedy);
register(kayles);
register(dawsonsKayles);
register(treblecross);
register(chomp);
register(euclidsGame);
register(fibonacciNim);
register(staircaseNim);
register(mooresNim);
register(nimble);
register(greenHackenbushStalk);
register(nodeKayles);
register(cram);
register(snort);
register(col);
register(domineering);
register(geographyGame);
register(turningTurtles);
register(goAtariCapture);
register(expectiminimax);
register(mctsUct);
register(proofNumberSearch);
register(retrogradeAnalysis);
register(dotsAndBoxes);
register(sprouts);
register(gnomeSort);
register(oddEvenTranspositionSort);
register(bitonicSort);
register(batcherOddEvenMergeSort);
register(boseNelsonSortingNetwork);
register(shearSort);
register(columnSort);
register(pancakeSort);
register(cycleSort);
register(strandSort);
register(tournamentSort);
register(treeSort);
register(splaySort);
register(librarySort);
register(blockSort);
register(mergeInsertionSort);
register(stoogeSort);
register(slowSort);
register(beadSort);
register(burstsort);
register(americanFlagSort);
register(pigeonholeSort);
register(flashSort);
register(proxmapSort);
register(samplesort);
register(externalKWayMergeSort);
register(polyphaseMergeSort);
register(cascadeMergeSort);
register(replacementSelectionSort);
register(sleepSort);
register(circleSort);
register(wiggleSort);
register(loserTreeMergeSort);
register(aksSortingNetwork);
register(stackPermutationSort);
register(dequeSortablePermutations);
register(genomeReversalSort);
register(cubeSort);
register(genomeTranspositionSort);
register(weakHeapSort);
register(naturalMergeSort);
register(bidirectionalSelectionSort);
register(fibonacciSearch);
register(rotatedArraySearch);
register(bitonicArraySearch);
register(peakFinding1d);
register(peakFinding2d);
register(saddlebackSearch);
register(quickselect);
register(medianOfMediansSelect);
register(sqrtDecompositionSearch);
register(fractionalCascading);
register(greedyBestFirstSearch);
register(beamSearch);
register(idaStarSearch);
register(smaStarSearch);
register(rbfsSearch);
register(uniformCostSearch);
register(branchAndBoundSearch);
register(backtrackingCspSearch);
register(ac3ArcConsistency);
register(minConflictsSearch);
register(dpllSatSearch);
register(walksatSearch);
register(majorityVoteSearch);
register(floydDuplicateSearch);
register(firstMissingPositiveSearch);
register(medianOfTwoSortedArrays);
register(kthInSortedMatrixSearch);
register(nearlySortedArraySearch);
register(twoPointerPairSumSearch);
register(sublistSearch);
register(sundayQuickShift);
register(horspoolSearch);
register(shiftOrBitap);
register(myersBitparallelApprox);
register(wuManberSearch);
register(bndmDawgMatching);
register(twoWayStringMatching);
register(suffixArraySearch);
register(lcpRmqQueries);
register(shortestUniqueSubstring);
register(distinctSubstringsCount);
register(runsViaLyndon);
register(palindromicFactorization);
register(needlemanWunschAlignment);
register(smithWatermanAlignment);
register(hirschbergAlignment);
register(bandedDpApproxMatching);
register(myersDiffOnd);
register(burrowsWheelerTransform);
register(lfMappingInversion);
register(fmIndexSearch);
register(moveToFrontTransform);
register(cykParsing);
register(earleyParsing);
register(ll1TableParsing);
register(lr0ShiftReduceParsing);
register(thompsonNfaConstruction);
register(subsetConstruction);
register(hopcroftDfaMinimization);
register(samOccurrenceQueries);
register(bomFactorOracleMatching);
register(setHorspoolSearch);
register(jaroWinklerSimilarity);
register(soundexPhoneticCoding);
register(porterStemmer);
register(shuntingYardParse);
register(dotPlotAlignment);
register(metaphonePhoneticCoding);
register(levenshteinAutomatonSearch);
register(qGramFilterSearch);
register(bytePairEncodingTokenization);
register(patienceDiff);
register(geneticAlgorithm);
register(particleSwarmOptimization);
register(antColonyOptimization);
register(tabuSearch);
register(gradientDescent1d);
register(newtonRaphsonRoot);
register(bisectionMethod);
register(goldenSectionSearch);
register(nelderMeadSimplex);
register(freivaldsCheck);
register(schwartzZippelIdentity);
register(diffieHellmanExchange);
register(secretaryProblem);
register(banditUcb);
register(simplexMethodLp);
register(gibbsSampling);
register(reservoirSampling);
register(morrisCounter);
register(hyperloglog);
register(misraGriesSummary);
register(greenwaldKhannaQuantiles);
register(minhashLsh);
register(consistentHashing);
register(lamportClock);
register(vectorClock);
register(chordDhtLookup);
register(merkleTreeProof);
register(gossipProtocol);
register(pagingAlgorithmsRace);
register(lz77Coding);
register(lz78Coding);
register(lzwCoding);
register(arithmeticCoding);
register(eliasGammaCoding);
register(skylineDivideConquer);
register(coinChangeCount);
register(coinChangeMinCoins);
register(rodCutting);
register(eggDrop);
register(palindromePartitioningMinCuts);
register(burstBalloons);
register(gridPathsCountWithObstacles);
register(minPathSumGrid);
register(dungeonGame);
register(distinctSubsequencesCount);
register(longestPalindromicSubseq);
register(wildcardMatching);
register(regexMatchingDp);
register(interleavingString);
register(stockIIITwoTransactions);
register(stockWithCooldown);
register(stockWithTransactionFee);
register(houseRobberLinear);
register(houseRobberCircular);
register(jumpGameMinJumps);
register(assignmentBitmaskDp);
register(profilePlugDpBrokenProfile);
register(sosDpSumOverSubsets);
register(convexHullTrickStatic);
register(liChaoSegmentTreeDp);
register(optimalGameStrategyPickEnds);
register(booleanParenthesization);
register(wordBreakCount);
register(catalanDpCounting);
register(derangementsDp);
register(tilingDpDominoTromino);
register(decodeWays);
register(longestArithmeticSubsequence);
register(boxStacking);
register(weightedIntervalScheduling);
register(activitySelectionGreedy);
register(longestPalindromicSubstring);
register(longestBitonicSubsequence);
register(maximalSquare);
register(maximalRectangleBinaryMatrix);
register(friendsPairingCount);
register(longestValidParenthesesDp);
register(trialDivisionFactorization);
register(fermatFactorization);
register(solovayStrassenTest);
register(lucasLehmerMersenne);
register(pohligHellmanDiscreteLog);
register(pollardRhoDiscreteLog);
register(montgomeryReduction);
register(ncrPrecomputeFactorials);
register(karatsubaMultiplication);
register(polynomialLongDivision);
register(continuedFractionsConvergents);
register(sternBrocotTree);
register(binaryGcdStein);
register(primeCountingMeisselLehmer);
register(segmentedSieve);
register(sieveOfAtkin);
register(primitiveRootSearch);
register(multiplicativeOrderFinding);
register(luDecomposition);
register(modularGaussianEliminationModP);
register(ellipticCurvePointAddition);
register(shamirSecretSharing);
register(lagrangeInterpolation);
register(grayCodeGeneration);
register(josephusProblem);
register(divisorSieveSigma);
register(henselLiftingRoot);
register(pollardPMinus1);
register(legendreSymbolEulerCriterion);
register(jacobiSymbol);
register(wilsonTheoremPrimeTest);
register(inclusionExclusionCounting);
register(linearCongruenceSolver);
register(additionChainBrauerStar);
register(lucasSequencesLehmer);
register(sieveOfSundaram);
register(factorialPrimeExponentLegendre);
register(integerSqrtNewton);
register(goldbachPartitionsSieve);
register(twinPrimeSieve);
register(bertrandPostulateCheck);
register(modularTetrationTowerEuler);
register(linearDiophantineTwoVar);
register(hammingCodeEncodeDecode);
register(bailliePswPrimality);
register(carmichaelKorseltTest);
register(elgamalEncryptionToy);
register(fareySequence);
register(evenPerfectNumbersEuler);
register(permutationRankFactoradic);
register(delaunayTriangulationIncremental);
register(voronoiDiagramFortune);
register(polygonTriangulationEarClipping);
register(polygonCentroid);
register(convexLayersOnionPeeling);
register(minEnclosingRectangleRotating);
register(kernelOfPolygon);
register(circleCircleIntersectionPoints);
register(lineCircleIntersectionPoints);
register(pickTheoremLatticePoints);
register(rectangleUnionKleeMeasureSweep);
register(alphaShapes);
register(kMeansLloyd);
register(dbscanClustering);
register(pointLineDualityTransform);
register(visibilityPolygon);
register(artGalleryGuardFisk);
register(shortestPathInPolygonFunnel);
register(lineArrangementIncremental);
register(incremental2dLinearProgramming);
register(circumcenterCircleThrough3Points);
register(gabrielGraphProximity);
register(hierarchicalAgglomerativeClustering);
register(latticePointsGaussCircle);
register(bresenhamLineRasterization);
register(midpointCircleRasterization);
register(sutherlandHodgmanPolygonClipping);
register(cohenSutherlandLineClipping);
register(pointSegmentDistance);
register(trapezoidalMapPointLocation);
register(douglasPeuckerPolylineSimplification);
register(marchingSquaresIsocontour);
register(largestEmptyCircleVoronoi);
register(circleUnionAreaSweep);
register(gjkConvexPolygonDistance);
register(hilbertCurvePointOrdering);
register(poissonDiskSampling);
register(skylineProblemSweep);
register(maxCollinearPointsLineThroughMost);
register(christofidesEuclideanTsp);
register(pointInConvexPolygonBinary);
register(convexPolygonIntersection);
register(aaTree);
register(scapegoatTree);
register(weightBalancedTree);
register(zipTree);
register(tangoTree);
register(orderStatisticTree);
register(intervalTree);
register(rangeTree2d);
register(cartesianTree);
register(rope);
register(gapBuffer);
register(pieceTable);
register(hashedArrayTree);
register(tieredVector);
register(sparseSet);
register(bitset);
register(roaringBitmap);
register(cuckooHashing);
register(robinHoodHashing);
register(hopscotchHashing);
register(coalescedHashing);
register(fksPerfectHashing);
register(extendibleHashing);
register(linearHashing);
register(rendezvousHashing);
register(countingBloomFilter);
register(cuckooFilter);
register(quotientFilter);
register(xorFilter);
register(minhashSketch);
register(tDigest);
register(kllSketch);
register(sparseTable);
register(disjointSparseTable);
register(fenwickTree2d);
register(mergeSortTree);
register(waveletTree);
register(waveletMatrix);
register(sqrtDecompositionArray);
register(quadtree);
register(octree);
register(kDTree);
register(ballTree);
register(rTree);
register(vpTree);
register(bkTree);
register(coverTree);
register(mTree);
register(bspTree);
register(gridFile);
register(kdbTree);
register(ubTree);
register(patriciaTrie);
register(binaryTrie);
register(adaptiveRadixTree);
register(hamt);
register(burstTrie);
register(doubleArrayTrie);
register(xFastTrie);
register(yFastTrie);
register(vanEmdeBoasTree);
register(concurrentTrie);
register(lsmTree);
register(fractalTree);
register(cacheObliviousBtree);
register(tTree);
register(orthogonalList);
register(doublyConnectedEdgeList);
register(adjacencySet);
register(linkCutTree);
register(eulerTourTree);
register(topTree);
register(hollowHeap);
register(softHeap);
register(minMaxHeap);
register(intervalHeap);
register(weakHeap);
register(twoThreeHeap);
register(radixHeap);
register(bucketHeap);
register(bHeapExternal);
register(funnelHeap);
register(quakeHeap);
register(beap);
register(brodalHeap);
register(calendarQueue);
register(minQueue);
register(steque);
register(twoStackQueue);
register(twoQueueStack);
register(lockFreeStack);
register(lruCache);
register(lfuCache);
register(arcCache);
register(clockCache);
register(persistentStack);
register(persistentArray);
register(persistentBst);
register(bankersQueue);
register(skewBinaryList);
register(vlist);
register(fingerTree);
register(rankSelectBitvector);
register(loudsTrie);
register(buddyAllocator);
register(slabAllocator);
register(freeListAllocator);
register(arenaAllocator);
register(dsuRollback);
register(unionFindDeletions);
register(twoThreeTree);
register(lockFreeQueueMichaelScott);
register(workStealingDequeChaseLev);
register(countSketch);

/**
 * Insert a module into the registry.
 *
 * @param module The algorithm module to register.
 * @throws When an algorithm with the same id is already registered, so that
 *         duplicate ids are caught at load time rather than silently shadowed.
 */
export function register(module: AlgorithmModule): void {
    if (registry.has(module.id)) {
        throw new Error(`Duplicate algorithm id: ${module.id}`);
    }
    registry.set(module.id, module);
}

/**
 * Look up an algorithm by its kebab-case id.
 *
 * @param id The algorithm identifier, e.g. `"binary-search"`.
 * @returns The matching module, or `null` when unknown.
 */
export function getAlgorithm(id: string): AlgorithmModule | null {
    return registry.get(id) ?? null;
}

/**
 * @returns Every registered algorithm module, in registration order.
 */
export function getAllAlgorithms(): AlgorithmModule[] {
    return [...registry.values()];
}
